autoCreateTopicsEnable: false
deleteTopicEnable: true

replicaCount: 3
defaultReplicationFactor: 3

zookeeper:
  replicaCount: 3

livenessProbe:
  initialDelaySeconds: 60

readinessProbe:
  initialDelaySeconds: 60
